global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.Rendering;
global using System.ComponentModel.DataAnnotations;
global using System.Linq;
global using System.Collections.Generic;
global using System.Threading.Tasks;
global using System.Diagnostics;
global using Microsoft.Extensions.Logging;